# Generated by Django 3.0.7 on 2020-07-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='alamat_kotakab',
            field=models.CharField(max_length=20, verbose_name='Alamat Kota/ Kab.'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nama_bank',
            field=models.CharField(help_text='Diutamakan Bank Mandiri', max_length=20),
        ),
        migrations.AlterField(
            model_name='coach',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
