# Generated by Django 3.0.7 on 2020-07-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0002_auto_20200709_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='bagi_hasil',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
