# Generated by Django 3.0.7 on 2020-07-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0003_coach_bagi_hasil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='tanggal_lahir',
            field=models.DateField(help_text='format "tahun-bulan-tanggal" (Contoh "2000-01-31")'),
        ),
    ]
