# Generated by Django 3.0.7 on 2020-07-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
        ('coach_app', '0002_auto_20200709_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=10)),
                ('kategori', models.CharField(choices=[('Bandung', 'Bandung'), ('Jakarta', 'Jakarta'), ('Dnurs', 'Dnurs')], max_length=10)),
                ('jumlah_siswa', models.IntegerField()),
                ('jumlah_pertemuan', models.IntegerField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['nama_produk'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diskon', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tanggal_transaksi', models.DateField()),
                ('tanggal_expired', models.DateField()),
                ('p1', models.DateField(blank=True, null=True, verbose_name='Pertemuan 1')),
                ('p2', models.DateField(blank=True, null=True, verbose_name='Pertemuan 2')),
                ('p3', models.DateField(blank=True, null=True, verbose_name='Pertemuan 3')),
                ('p4', models.DateField(blank=True, null=True, verbose_name='Pertemuan 4')),
                ('p5', models.DateField(blank=True, null=True, verbose_name='Pertemuan 5')),
                ('p6', models.DateField(blank=True, null=True, verbose_name='Pertemuan 6')),
                ('p7', models.DateField(blank=True, null=True, verbose_name='Pertemuan 7')),
                ('p8', models.DateField(blank=True, null=True, verbose_name='Pertemuan 8')),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach_app.Coach')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.Product')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.Student')),
            ],
            options={
                'ordering': ['student'],
            },
        ),
    ]
