# Generated by Django 3.0.7 on 2020-07-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harga',
            field=models.IntegerField(),
        ),
    ]
