# Generated by Django 3.0.7 on 2020-07-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_order_arsip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='p1_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p2_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p3_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p4_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p5_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p6_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p7_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p8_a',
            field=models.BooleanField(default=False),
        ),
    ]
