# Generated by Django 3.0.8 on 2020-07-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_auto_20200714_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='p1_a',
            field=models.BooleanField(default=False),
        ),
    ]
