# Generated by Django 3.0.8 on 2020-07-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_auto_20200714_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='p2_a',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p3_a',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p4_a',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p5_a',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p6_a',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p7_a',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p8_a',
            field=models.BooleanField(),
        ),
    ]
