# Generated by Django 3.0.7 on 2020-07-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_auto_20200714_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='p1_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p2_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p3_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p4_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p5_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p6_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p7_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='p8_c',
            field=models.BooleanField(default=False),
        ),
    ]
