# Generated by Django 3.0.7 on 2020-07-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_auto_20200715_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='p1_c',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p2_c',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p3_c',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p4_c',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p5_c',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p6_c',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p7_c',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='p8_c',
            field=models.BooleanField(),
        ),
    ]
