# Generated by Django 3.0.7 on 2020-07-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeed',
            name='waktu_post',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
