# Generated by Django 3.0.7 on 2020-07-09 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=50)),
                ('nama_panggilan', models.CharField(max_length=10)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('tempat_lahir', models.CharField(max_length=10)),
                ('tanggal_lahir', models.DateField(help_text='YYYY-MM-DD')),
                ('alamat_tinggal', models.CharField(max_length=100)),
                ('alamat_kotakab', models.CharField(max_length=20, verbose_name='Alamat Kota/ Kab.')),
                ('nomor_ponsel', models.CharField(max_length=20)),
                ('alamat_email', models.EmailField(max_length=254)),
                ('deskripsi', models.TextField(blank=True, help_text='latar belakang, pendidikan, keahlian', max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nama_lengkap'],
            },
        ),
    ]
