# Generated by Django 3.0.7 on 2020-07-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='afiliasi',
            field=models.CharField(blank=True, choices=[('Dnurs', 'Dnurs')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
