# Generated by Django 3.0.7 on 2020-07-13 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_auto_20200710_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengenalan_air_1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Pengaturan Nafas')),
                ('pengenalan_air_2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Mengapung Telungkup dan Telentang')),
                ('pengenalan_air_3', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Teknik Meluncur')),
                ('komentar', models.TextField(blank=True, max_length=200)),
                ('waktu_post', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-waktu_post'],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-nama_lengkap']},
        ),
        migrations.AlterField(
            model_name='student',
            name='deskripsi',
            field=models.TextField(blank=True, help_text='harapan latihan, penyakit, kebiasaan, dll', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='tanggal_lahir',
            field=models.DateField(help_text='format "tahun-bulan-tanggal" (Contoh "2000-01-31")'),
        ),
    ]
