# Generated by Django 3.0.7 on 2020-07-13 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_auto_20200712_1658'),
        ('student_app', '0003_auto_20200713_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapor',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.Order'),
        ),
    ]
