# Generated by Django 3.0.7 on 2020-07-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_auto_20200713_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapor',
            name='waktu_post',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
